Highcharts.chart('container', {

    title: {
        text: 'De donde y hacia donde van los chilenos (promedio mensual)',
        style: {
            fontFamily: 'Poppins Light',
        }
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. From {point.from} to {point.to}: {point.weight}.'
        }
    },

    series: [{
        keys: ['from', 'to', 'weight'],
        data: [
            ['Tarapaca', 'Antofagasta', 862],
            ['Tarapaca', 'Atacama', 90],
            ['Tarapaca', 'Coquimbo', 202],
            ['Tarapaca', 'Valparaiso', 113],
            ['Tarapaca', 'OHiggins', 30],
            ['Tarapaca', 'Maule', 30],
            ['Tarapaca', 'Bio-Bio', 24],
            ['Tarapaca', 'La Araucania', 12],
            ['Tarapaca', 'Los lagos', 22],
            ['Tarapaca', 'Aysen', 16],
            ['Tarapaca', 'Magallanes', 27],
            ['Tarapaca', 'Metropolitana', 291],
            ['Tarapaca', 'Los Rios', 17],
            ['Tarapaca', 'Arica', 1492],
            ['Tarapaca', 'Ñuble', 31],
            ['Antofagasta', 'Tarapaca', 1781],
            ['Antofagasta', 'Atacama', 527],
            ['Antofagasta', 'Coquimbo', 750],
            ['Antofagasta', 'Valparaiso', 118],
            ['Antofagasta', 'OHiggins', 32],
            ['Antofagasta', 'Maule', 28],
            ['Antofagasta', 'Bio-Bio', 59],
            ['Antofagasta', 'La Araucania', 48],
            ['Antofagasta', 'Los Lagos', 52],
            ['Antofagasta', 'Aysen', 40],
            ['Antofagasta', 'Magallanes', 68],
            ['Antofagasta', 'Metropolitana', 288],
            ['Antofagasta', 'Los Rios', 195]
            ['Antofagasta', 'Arica', 795],
            ['Antofagasta', 'Ñuble', 19],
            ['Atacama', 'Tarapaca', 107],
            ['Atacama', 'Antofagasta', 645],
            ['Atacama', 'Coquimbo', 762],
            ['Atacama', 'Valparaiso', 93],
            ['Atacama', 'OHiggins', 25],
            ['Atacama', 'Maule', 17],
            ['Atacama', 'Bio-Bio', 24],
            ['Atacama', 'La Araucania', 10],
            ['Atacama', 'Los Lagos', 37],
            ['Atacama', 'Aysen', 16],
            ['Atacama', 'Magallanes', 27],
            ['Atacama', 'Metropolitana', 153], 
            ['Atacama', 'Los Rios',18]
            ['Atacama', 'Arica', 110],
            ['Atacama', 'Ñuble', 16],
            ['Coquimbo', 'Tarapaca', 160],
            ['Coquimbo', 'Antofagasta', 556],
            ['Coquimbo', 'Atacama', 838],
            ['Coquimbo', 'Valparaiso', 156],
            ['Coquimbo', 'OHiggins', 46],
            ['Coquimbo', 'Maule', 23],
            ['Coquimbo', 'Bio-Bio', 25],
            ['Coquimbo', 'La Araucania', 35],
            ['Coquimbo', 'Los Lagos', 31],
            ['Coquimbo', 'Aysen', 20],
            ['Coquimbo', 'Magallanes', 30],
            ['Coquimbo', 'Metropolitana', 349],
            ['Coquimbo', 'Los Rios', 22],
            ['Coquimbo', 'Arica', 136],
            ['Coquimbo', 'Ñuble',19]
            ['Valparaiso', 'Tarapaca', 128],
            ['Valparaiso', 'Antofagasta', 181],
            ['Valparaiso', 'Atacama', 115],
            ['Valparaiso', 'Coquimbo', 370],
            ['Valparaiso', 'OHiggins', 117],
            ['Valparaiso', 'Maule', 75],
            ['Valparaiso', 'Bio-Bio', 124],
            ['Valparaiso', 'La Araucania', 56],
            ['Valparaiso', 'Los Lagos', 46],
            ['Valparaiso', 'Aysen', 26],
            ['Valparaiso', 'Magallanes', 27],
            ['Valparaiso', 'Metropolitana', 517],
            ['Valparaiso', 'Los Rios', 62]
            ['Valparaiso', 'Arica', 131],
            ['Valparaiso', 'Ñuble', 46],
            ['OHiggins', 'Tarapaca', 81],
            ['OHiggins', 'Antofagasta', 122],
            ['OHiggins', 'Atacama', 34],
            ['OHiggins', 'Coquimbo', 217],
            ['OHiggins', 'Valparaiso', 494],
            ['OHiggins', 'Maule', 198],
            ['OHiggins', 'Bio-Bio', 69],
            ['OHiggins', 'La Araucania', 45],
            ['OHiggins', 'Los Lagos', 64],
            ['OHiggins', 'Aysen', 22],
            ['OHiggins', 'Magallanes', 37],
            ['OHiggins', 'Metropolitana', 512],
            ['OHiggins', 'Los Rios', 86],
            ['OHiggins', 'Arica', 4],
            ['OHiggins', 'Ñuble', 84],
            ['Maule', 'Tarpaca', 58],
            ['Maule', 'Antofagasta', 42],
            ['Maule', 'Atacama', 30],
            ['Maule', 'Coquimbo', 18],
            ['Maule', 'Valparaiso', 182],
            ['Maule', 'OHiggins', 122],
            ['Maule', 'Bio-Bio', 100],
            ['Maule', 'La Araucania', 30],
            ['Maule', 'Los Lagos', 78],
            ['Maule', 'Aysen', 16],
            ['Maule', 'Magallanes', 22],
            ['Maule', 'Metropolitana', 195],
            ['Maule', 'Los Rios', 142],
            ['Maule', 'Arica', 75],
            ['Maule', 'Ñuble', 242],
            ['Bio-Bio', 'Tarapaca', 84],
            ['Bio-Bio', 'Antofagasta', 83],
            ['Bio-Bio', 'Atacama', 27],
            ['Bio-Bio', 'Coquimbo', 24],
            ['Bio-Bio', 'Valparaiso', 114],
            ['Bio-Bio', 'OHiggins', 50],
            ['Bio-Bio', 'Maule', 143],
            ['Bio-Bio', 'La Araucania', 88],
            ['Bio-Bio', 'Los Lagos', 130],
            ['Bio-Bio', 'Aysen', 15],
            ['Bio-Bio', 'Magallanes', 67],
            ['Bio-Bio', 'Metropolitana', 314],
            ['Bio-Bio', 'Los Rios', 314],
            ['Bio-Bio', 'Arica', 52],
            ['Bio-Bio', 'Ñuble', 1307],
            ['La Araucania', 'Tarapaca', 83],
            ['La Araucania', 'Antofagasta', 69],
            ['La Araucania', 'Atacama', 230],
            ['La Araucania', 'Coquimbo', 72],
            ['La Araucania', 'Valparaiso', 97],
            ['La Araucania', 'OHiggins', 62],
            ['La Araucania', 'Maule', 120],
            ['La Araucania', 'Bio-Bio', 290],
            ['La Araucania', 'Los Lagos', 43],
            ['La Araucania', 'Aysen', 120],
            ['La Araucania', 'Magallanes', 81],
            ['La Araucania', 'Metropolitana', 407],
            ['La Araucania', 'Los Rios', 387],
            ['La Araucania', 'Arica', 6],
            ['La Araucania', 'Ñuble', 49],
            ['Los Lagos', 'Tarapaca', 5],
            ['Los Lagos', 'Antofagasta', 5],
            ['Los Lagos', 'Atacama', 5],
            ['Los Lagos', 'Coquimbo', 5],
            ['Los Lagos', 'Valparaiso', 5],
            ['Los Lagos', 'OHiggins', 5],
            ['Los Lagos', 'Maule', 5],
            ['Los Lagos', 'Bio-Bio', 5],
            ['Los Lagos', 'La Araucania', 5],
            ['Los Lagos', 'Los Lagos', 5],
            ['Los Lagos', 'Aysen', 5],
            ['Los Lagos', 'Magallanes', 5],
            ['Los Lagos', 'Metropolitana', 5],
            ['Los Lagos', 'Arica', 5],
            ['Los Lagos', 'Ñuble', 5],
            ['Aysen', 'Tarapaca', 3],
            ['Aysen', 'Antofagasta', 3],
            ['Aysen', 'Atacama', 3],
            ['Aysen', 'Coquimbo', 3],
            ['Aysen', 'Valparaiso', 3],
            ['Aysen', 'OHiggins', 3],
            ['Aysen', 'Maule', 3],
            ['Aysen', 'Bio-Bio', 3],
            ['Aysen', 'La Araucania', 3],
            ['Aysen', 'Los Lagos', 3],
            ['Aysen', 'Aysen', 3],
            ['Aysen', 'Magallanes', 3],
            ['Aysen', 'Metropolitana', 3],
            ['Aysen', 'Arica', 3],
            ['Aysen', 'Ñuble', 3],
            ['Magallanes', 'Tarapaca', 34],
            ['Magallanes', 'Antofagasta', 15],
            ['Magallanes', 'Atacama', 79],
            ['Magallanes', 'Coquimbo', 21],
            ['Magallanes', 'Valparaiso', 73],
            ['Magallanes', 'OHiggins', 51],
            ['Magallanes', 'Maule', 37],
            ['Magallanes', 'Bio-Bio', 92],
            ['Magallanes', 'La Araucania', 120],
            ['Magallanes', 'Los Lagos', 210],
            ['Magallanes', 'Aysen', 139],
            ['Magallanes', 'Magallanes', 5],
            ['Magallanes', 'Metropolitana', 120],
            ['Magallanes', 'Arica', 5],
            ['Magallanes', 'Ñuble', 72],
            ['Metropolitana', 'Tarapaca', 195],
            ['Metropolitana', 'Antofagasta', 202],
            ['Metropolitana', 'Atacama', 403],
            ['Metropolitana', 'Coquimbo', 62],
            ['Metropolitana', 'Valparaiso', 702],
            ['Metropolitana', 'OHiggins', 703],
            ['Metropolitana', 'Maule', 93],
            ['Metropolitana', 'Bio-Bio', 193],
            ['Metropolitana', 'La Araucania', 276],
            ['Metropolitana', 'Los Lagos', 509],
            ['Metropolitana', 'Aysen', 302],
            ['Metropolitana', 'Magallanes', 120],
            ['Metropolitana', 'Los Rios', 370],
            ['Metropolitana', 'Arica', 280],
            ['Metropolitana', 'Ñuble', 120],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Los Rios', 'Los Rios', 63],
            ['Arica', 'Tarapaca', 3],
            ['Arica', 'Antofagasta', 3],
            ['Arica', 'Atacama', 3],
            ['Arica', 'Coquimbo', 3],
            ['Arica', 'Valparaiso', 3],
            ['Arica', 'OHiggins', 3],
            ['Arica', 'Maule', 3],
            ['Arica', 'Bio-Bio', 3],
            ['Arica', 'La Araucania', 3],
            ['Arica', 'Los Lagos', 3],
            ['Arica', 'Aysen', 3],
            ['Arica', 'Magallanes', 3],
            ['Arica', 'Metropolitana', 3],
            ['Arica', 'Los Rios', 63],
            ['Arica', 'Ñuble', 3],
            ['Ñuble', 'Tarapaca', 3],
            ['Ñuble', 'Antofagasta', 3],
            ['Ñuble', 'Atacama', 3],
            ['Ñuble', 'Coquimbo', 3],
            ['Ñuble', 'Valparaiso', 300],
            ['Ñuble', 'OHiggins', 3],
            ['Ñuble', 'Maule', 3],
            ['Ñuble', 'Bio-Bio', 3],
            ['Ñuble', 'La Araucania', 3],
            ['Ñuble', 'Los Lagos', 3],
            ['Ñuble', 'Aysen', 3],
            ['Ñuble', 'Magallanes', 3],
            ['Ñuble', 'Metropolitana', 3],
            ['Ñuble', 'Los Rios', 3],
            ['Ñuble', 'Arica', 3],
        ],
        type: 'dependencywheel',
        name: 'Dependency wheel series',
        dataLabels: {
            color: '#333',
            style: {
                textOutline: 'none',
                fontFamily: 'Poppins Medium',
            },
            textPath: {
                enabled: true
            },
            distance: 10
        },
        size: '95%'
    }]

});
