Highcharts.chart('container', {

    title: {
        text: 'Highcharts Dependency Wheel'
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. From {point.from} to {point.to}: {point.weight}.'
        }
    },

    series: [{
        keys: ['from', 'to', 'weight'],
        data: [
            ['Tarapaca', 'Tarapaca', 5],
            ['Tarapaca', 'Antofagasta', 1],
            ['Tarapaca', 'Atacama', 1],
            ['Tarapaca', 'Coquimbo', 1],
            ['Tarapaca', 'Valparaiso', 1],
            ['Tarapaca', 'OHiggins', 5],
            ['Tarapaca', 'Maule', 1],
            ['Tarapaca', 'Bio-Bio', 1],
            ['Tarapaca', 'La Araucania', 1],
            ['Tarapaca', 'Los lagos', 5],
            ['Tarapaca', 'Aysen', 1],
            ['Tarapaca', 'Magallanes', 1],
            ['Tarapaca', 'Metropolitana', 1],
            ['Tarapaca', 'Los rios', 1],
            ['Tarapaca', 'Arica', 5],
            ['Tarapaca', 'Ñuble', 2],
            ['Antofagasta', 'Tarapaca', 1],
            ['Antofagasta', 'Antofagasta', 1],
            ['Antofagasta', 'Atacama', 3],
            ['Antofagasta', 'Coquimbo', 1],
            ['Antofagasta', 'Valparaiso', 3],
            ['Antofagasta', 'OHiggins', 3],
            ['Antofagasta', 'Maule', 3],
            ['Antofagasta', 'Bio-Bio', 1],
            ['Antofagasta', 'La Araucania', 1],
            ['Antofagasta', 'Los Lagos', 3],
            ['Antofagasta', 'Aysen', 1],
            ['Antofagasta', 'Magallanes', 1],
            ['Antofagasta', 'Metropolitana', 1],
            ['Antofagasta', 'Arica', 2],
            ['Antofagasta', 'Ñuble', 7],
            ['Atacama', 'Tarapaca', 5],
            ['Atacama', 'Antofagasta', 1],
            ['Atacama', 'Atacama', 1],
            ['Atacama', 'Coquimbo', 1],
            ['Atacama', 'Valparaiso', 1],
            ['Atacama', 'OHiggins', 1],
            ['Atacama', 'Maule', 1],
            ['Atacama', 'Bio-Bio', 1],
            ['Atacama', 'La Araucania', 1],
            ['Atacama', 'Los Lagos', 1],
            ['Atacama', 'Aysen', 1],
            ['Atacama', 'Magallanes', 1],
            ['Atacama', 'Metropolitana', 1],
            ['Atacama', 'Arica', 1],
            ['Atacama', 'Ñuble', 1],
            ['Coquimbo', 'Tarapaca', 3],
            ['Coquimbo', 'Antofagasta', 3],
            ['Coquimbo', 'Atacama', 3],
            ['Coquimbo', 'Coquimbo', 3],
            ['Coquimbo', 'Valparaiso', 3],
            ['Coquimbo', 'OHiggins', 3],
            ['Coquimbo', 'Maule', 3],
            ['Coquimbo', 'Bio-Bio', 3],
            ['Coquimbo', 'La Araucania', 3],
            ['Coquimbo', 'Los Lagos', 3],
            ['Coquimbo', 'Aysen', 3],
            ['Coquimbo', 'Magallanes', 3],
            ['Coquimbo', 'Metropolitana', 3],
            ['Coquimbo', 'Arica', 3],
            ['Coquimbo', 'Ñuble', 3],
            ['Valparaiso', 'Tarapaca', 5],
            ['Valparaiso', 'Antofagasta', 5],
            ['Valparaiso', 'Atacama', 5],
            ['Valparaiso', 'Coquimbo', 5],
            ['Valparaiso', 'Valparaiso', 5],
            ['Valparaiso', 'OHiggins', 5],
            ['Valparaiso', 'Maule', 5],
            ['Valparaiso', 'Bio-Bio', 5],
            ['Valparaiso', 'La Araucania', 5],
            ['Valparaiso', 'Los Lagos', 5],
            ['Valparaiso', 'Aysen', 5],
            ['Valparaiso', 'Magallanes', 5],
            ['Valparaiso', 'Metropolitana', 5],
            ['Valparaiso', 'Arica', 5],
            ['Valparaiso', 'Ñuble', 5],
            ['OHiggins', 'Tarapaca', 1],
            ['OHiggins', 'Antofagasta', 1],
            ['OHiggins', 'Atacama', 1],
            ['OHiggins', 'Coquimbo', 1],
            ['OHiggins', 'Valparaiso', 1],
            ['OHiggins', 'OHiggins', 1],
            ['OHiggins', 'Maule', 1],
            ['OHiggins', 'Bio-Bio', 1],
            ['OHiggins', 'La Araucania', 1],
            ['OHiggins', 'Los Lagos', 1],
            ['OHiggins', 'Aysen', 1],
            ['OHiggins', 'Magallanes', 1],
            ['OHiggins', 'Metropolitana', 1],
            ['OHiggins', 'Arica', 1],
            ['OHiggins', 'Ñuble', 3],
            ['Maule', 'Tarpaca', 5],
            ['Maule', 'Antofagasta', 5],
            ['Maule', 'Atacama', 5],
            ['Maule', 'Coquimbo', 5],
            ['Maule', 'Valparaiso', 5],
            ['Maule', 'OHiggins', 5],
            ['Maule', 'Maule', 5],
            ['Maule', 'Bio-Bio', 5],
            ['Maule', 'La Araucania', 5],
            ['Maule', 'Los Lagos', 5],
            ['Maule', 'Aysen', 5],
            ['Maule', 'Magallanes', 5],
            ['Maule', 'Metropolitana', 5],
            ['Maule', 'Arica', 5],
            ['Maule', 'Ñuble', 5],
            ['Bio-Bio', 'Tarapaca', 1],
            ['Bio-Bio', 'Antofagasta', 1],
            ['Bio-Bio', 'Atacama', 1],
            ['Bio-Bio', 'Coquimbo', 1],
            ['Bio-Bio', 'Valparaiso', 1],
            ['Bio-Bio', 'OHiggins', 1],
            ['Bio-Bio', 'Maule', 1],
            ['Bio-Bio', 'Bio-Bio', 1],
            ['Bio-Bio', 'La Araucania', 1],
            ['Bio-Bio', 'Los Lagos', 1],
            ['Bio-Bio', 'Aysen', 1],
            ['Bio-Bio', 'Magallanes', 1],
            ['Bio-Bio', 'Metropolitana', 1],
            ['Bio-Bio', 'Arica', 1],
            ['Bio-Bio', 'Ñuble', 1],
            ['La Araucania', 'Tarapaca', 3],
            ['La Araucania', 'Antofagasta', 3],
            ['La Araucania', 'Atacama', 3],
            ['La Araucania', 'Coquimbo', 3],
            ['La Araucania', 'Valparaiso', 3],
            ['La Araucania', 'OHiggins', 3],
            ['La Araucania', 'Maule', 3],
            ['La Araucania', 'Bio-Bio', 3],
            ['La Araucania', 'La Araucania', 3],
            ['La Araucania', 'Los Lagos', 3],
            ['La Araucania', 'Aysen', 3],
            ['La Araucania', 'Magallanes', 3],
            ['La Araucania', 'Metropolitana', 3],
            ['La Araucania', 'Arica', 3],
            ['La Araucania', 'Ñuble', 3],
            ['Los Lagos', 'Tarapaca', 5],
            ['Los Lagos', 'Antofagasta', 5],
            ['Los Lagos', 'Atacama', 5],
            ['Los Lagos', 'Coquimbo', 5],
            ['Los Lagos', 'Valparaiso', 5],
            ['Los Lagos', 'OHiggins', 5],
            ['Los Lagos', 'Maule', 5],
            ['Los Lagos', 'Bio-Bio', 5],
            ['Los Lagos', 'La Araucania', 5],
            ['Los Lagos', 'Los Lagos', 5],
            ['Los Lagos', 'Aysen', 5],
            ['Los Lagos', 'Magallanes', 5],
            ['Los Lagos', 'Metropolitana', 5],
            ['Los Lagos', 'Arica', 5],
            ['Los Lagos', 'Ñuble', 5],
            ['Aysen', 'Tarapaca', 3],
            ['Aysen', 'Antofagasta', 3],
            ['Aysen', 'Atacama', 3],
            ['Aysen', 'Coquimbo', 3],
            ['Aysen', 'Valparaiso', 3],
            ['Aysen', 'OHiggins', 3],
            ['Aysen', 'Maule', 3],
            ['Aysen', 'Bio-Bio', 3],
            ['Aysen', 'La Araucania', 3],
            ['Aysen', 'Los Lagos', 3],
            ['Aysen', 'Aysen', 3],
            ['Aysen', 'Magallanes', 3],
            ['Aysen', 'Metropolitana', 3],
            ['Aysen', 'Arica', 3],
            ['Aysen', 'Ñuble', 3],
            ['Magallanes', 'Tarapaca', 5],
            ['Magallanes', 'Antofagasta', 5],
            ['Magallanes', 'Atacama', 5],
            ['Magallanes', 'Coquimbo', 5],
            ['Magallanes', 'Valparaiso', 5],
            ['Magallanes', 'OHiggins', 5],
            ['Magallanes', 'Maule', 5],
            ['Magallanes', 'Bio-Bio', 5],
            ['Magallanes', 'La Araucania', 5],
            ['Magallanes', 'Los Lagos', 5],
            ['Magallanes', 'Aysen', 5],
            ['Magallanes', 'Magallanes', 5],
            ['Magallanes', 'Metropolitana', 5],
            ['Magallanes', 'Arica', 5],
            ['Magallanes', 'Ñuble', 5],
            ['Metropolitana', 'Tarapaca', 1],
            ['Metropolitana', 'Antofagasta', 1],
            ['Metropolitana', 'Atacama', 1],
            ['Metropolitana', 'Coquimbo', 1],
            ['Metropolitana', 'Valparaiso', 1],
            ['Metropolitana', 'OHiggins', 1],
            ['Metropolitana', 'Maule', 1],
            ['Metropolitana', 'Bio-Bio', 1],
            ['Metropolitana', 'La Araucania', 1],
            ['Metropolitana', 'Los Lagos', 1],
            ['Metropolitana', 'Aysen', 1],
            ['Metropolitana', 'Magallanes', 1],
            ['Metropolitana', 'Metropolitana', 1],
            ['Metropolitana', 'Arica', 1],
            ['Metropolitana', 'Ñuble', 1],
            ['Arica', 'Tarapaca', 3],
            ['Arica', 'Antofagasta', 3],
            ['Arica', 'Atacama', 3],
            ['Arica', 'Coquimbo', 3],
            ['Arica', 'Valparaiso', 3],
            ['Arica', 'OHiggins', 3],
            ['Arica', 'Maule', 3],
            ['Arica', 'Bio-Bio', 3],
            ['Arica', 'La Araucania', 3],
            ['Arica', 'Los Lagos', 3],
            ['Arica', 'Aysen', 3],
            ['Arica', 'Magallanes', 3],
            ['Arica', 'Metropolitana', 3],
            ['Arica', 'Arica', 3],
            ['Arica', 'Ñuble', 3],
            ['Ñuble', 'Tarapaca', 3],
            ['Ñuble', 'Antofagasta', 3],
            ['Ñuble', 'Atacama', 3],
            ['Ñuble', 'Coquimbo', 3],
            ['Ñuble', 'Valparaiso', 3],
            ['Ñuble', 'OHiggins', 3],
            ['Ñuble', 'Maule', 3],
            ['Ñuble', 'Bio-Bio', 3],
            ['Ñuble', 'La Araucania', 3],
            ['Ñuble', 'Los Lagos', 3],
            ['Ñuble', 'Aysen', 3],
            ['Ñuble', 'Magallanes', 3],
            ['Ñuble', 'Metropolitana', 3],
            ['Ñuble', 'Arica', 3],
            ['Ñuble', 'Ñuble', 3],
        ],
        type: 'dependencywheel',
        name: 'Dependency wheel series',
        dataLabels: {
            color: '#333',
            style: {
                textOutline: 'none'
            },
            textPath: {
                enabled: true
            },
            distance: 10
        },
        size: '95%'
    }]

});
